config/routes.rb
Rails.application.routes.draw do

  get 'status' => 'status#index', :via => :get

  get 'how-it-works' => 'welcome#how_it_works', :via => :get
  get 'privacy-policy' => 'welcome#privacy_policy', :via => :get

  root 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { sessions: "api/v1/sessions" }
      resources :records
    end
  end

  match '/api/v1/users/sign_in' => 'application#index', via: :options

  match '/records/stats' => 'records#stats', :via => :get
  match '/records/aggregates' => 'records#aggregates', :via => :get
  match '/records/wordcloud' => 'records#wordcloud', :via => :get
  match '/records/log' => 'records#log', :via => :get
  match '/records/export' => 'records#export', :via => :get
  match '/records/reminder' => 'records#reminder', :via => :get


  match '/care/for' => 'care#receivers', :via => :get

  resources :records

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_how_it_works.html.haml
.row.centered-images
  .col-xs-12.col-sm-12.col-md-8
    %h2 1. Track how you feel
    .screen-shots-capture
      = image_tag("howareyou.png")
      = image_tag("howareyouandroid.png")

    Whenever you feel like (we recommend at least daily) capture how you feel using the app.
  .col-xs-12.col-sm-12.col-md-4
    %h2 2. Get insights
    = image_tag("stats.png")

app/views/welcome/how_it_works.html.haml
- content_for(:title, "How it works?")

%h1 How it works?
.container
  = render 'how_it_works'
  .row
    .col-xs-12
      %h2 What different states mean
  .row
    .col-xs-12.col-sm-6
      .panel.panel-default.panel-health-state
        .panel-heading
          Healthy
        .panel-body
          .panel-health-body-content.panel-health-body-content-healthy
            .panel-health-body-text
              You feeling healthy, great!


    .col-xs-12.col-sm-6
      .panel.panel-default.panel-health-state
        .panel-heading
          Coming Down
        .panel-body
          .panel-health-body-content.panel-health-body-content-coming-down
            .panel-health-body-text
              You don't feel quite right, maybe you getting down with cold?
  .row
    .col-xs-12.col-sm-6
      .panel.panel-default.panel-health-state
        .panel-heading
          Sick
        .panel-body
          .panel-health-body-content.panel-health-body-content-sick
            .panel-health-body-text
              No doubt, you feel sick. You probably should see a doctor and stay home.
    .col-xs-12.col-sm-6
      .panel.panel-default.panel-health-state
        .panel-heading
          Recovering
        .panel-body
          .panel-health-body-content.panel-health-body-content-recovery
            .panel-health-body-text
              Still not 100% healthy, but getting better.

- unless user_signed_in?
  %p

  %h2 Interested?

  To start simply
  %a{:href => new_user_registration_path, :rel => 'nofollow'}
    %button.btn.btn-primary
      create free account

app/views/welcome/index.html.haml
.jumbotron
  .container
    .row
      .col-xs-12.col-md-6
        %h1
          HeCoSiRe
        %p
          Track your health.
          %br
          %br

        %p HeCoSiRe is a health tracker. Use it to track how you feel and get insight into your health.

        - if user_signed_in?
          %a{:href => records_path, :rel => 'nofollow'}
            %button.btn.btn-success
              Manage your records
          %a{:href => new_record_path, :rel => 'nofollow'}
            %button.btn.btn-primary
              Report how you feel

        - else
          To start simply
          %a{:href => new_user_registration_path, :rel => 'nofollow'}
            %button.btn.btn-primary
              create free account
          or
          = link_to('login', new_user_session_path, :rel => 'nofollow')
          if you already have one.

        .facebook
          #fb-root
          .fb-like{"data-action" => "like", "data-href" => "http://hecosire.com/", "data-layout" => "standard", "data-share" => "true", "data-show-faces" => "true"}

      .col-xs-12.col-md-6
        %iframe#hecosire-video{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "//www.youtube.com/embed/wICKl0kYK9M?rel=0", :width => "100%"}



%h1 How it works

.container
  = render 'how_it_works'

  = link_to('Find out more', how_it_works_path)

.container
  .row
    .col-xs-12.col-sm-6
      %h1 How to track
      You can track using website or with our Android app:

      %a{:href => "https://play.google.com/store/apps/details?id=hecosire.com.hecosireapp"}
        %img{:alt => "Android app on Google Play", :src => "https://developer.android.com/images/brand/en_app_rgb_wo_45.png"}/

      %h2 The benefit

      %p The data you capture will help you reflect on your health.

      %p We provide personal log, cloud tags and useful graphs that let you do it.

      %p Overtime we hope to provide insights that will allow you to be more often healthy.

      - unless user_signed_in?
        %p

        %h2 Interested?

        To start simply
        %a{:href => new_user_registration_path, :rel => 'nofollow'}
          %button.btn.btn-primary
            create free account
    .col-xs-12.col-sm-6
      %h2 As seen in
      %a{:href => "http://pixelhealth.net/2015/04/24/the-friday-interview-grzegorz-dziemidowicz-hecosire/"}
        %img{:alt => "PixelHealth interview", :src => "http://pixelhealth.net/wp-content/uploads/2014/04/pixel-health1.png"}/

      %h2 How is everyone feeling?

      Glad you asked,
      = link_to('find out here how other users are feeling.', status_path)




  :javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/welcome/privacy_policy.html.haml
%h1 Privacy Policy
This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

%h2 What personal information do we collect from the people that visit our blog, website or app?

When ordering or registering on our site, as appropriate, you may be asked to enter your email address or other details to help you with your experience.

%h2 When do we collect information?

We collect information from you when you register on our site or enter information on our site.


%h2 How do we use your information?

We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

%li To personalize user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.
%li To send periodic emails regarding your order or other products and services.

%h2 How do we protect visitor information?

We do not use vulnerability scanning and/or scanning to PCI standards.
We do not use Malware Scanning.

We do not use an SSL certificate
%li We do not need an SSL because: We are working on getting one..

%h2 Do we use 'cookies'?

Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.

We use cookies to:
%li Understand and save user's preferences for future visits.
%li Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third party services that track this information on our behalf.

%p You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.

%p If users disable cookies in their browser:

%p If you disable cookies off, some features will be disabled It will turn off some of the features that make your site experience more efficient and some of our services will not function properly.


%h2 Third Party Disclosure

%p We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information.

%h2 Third party links

%p Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.


We have implemented the following:
%li Demographics and Interests Reporting



%h2 How does our site handle do not track signals?
We don't honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place. We don't honor them because:
TODO

%h2 Does our site allow third party behavioral tracking?
It's also important to note that we do not allow third party behavioral tracking

%h2 COPPA (Children Online Privacy Protection Act)

%p When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.

%p We do not specifically market to children under 13.

%h2 Fair Information Practices

%p The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.

In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
We will notify the users via email
%li Within 7 business days
We will notify the users via in site notification
%li Within 7 business days

%p We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.

%h2 CAN SPAM Act

%p The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.

%p We collect your email address in order to:

%p To be in accordance with CANSPAM we agree to the following:

%p If at any time you would like to unsubscribe from receiving future emails, you can email us at
and we will promptly remove you from ALL correspondence.

%p If there are any questions regarding this privacy policy you may contact us using the information below.

%p privacy@hecosire.com

%p
  %i Last Edited on 2015-05-08