config/routes.rb
Rails.application.routes.draw do

  get 'status' => 'status#index', :via => :get

  get 'how-it-works' => 'welcome#how_it_works', :via => :get
  get 'privacy-policy' => 'welcome#privacy_policy', :via => :get

  root 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { sessions: "api/v1/sessions" }
      resources :records
    end
  end

  match '/api/v1/users/sign_in' => 'application#index', via: :options

  match '/records/stats' => 'records#stats', :via => :get
  match '/records/aggregates' => 'records#aggregates', :via => :get
  match '/records/wordcloud' => 'records#wordcloud', :via => :get
  match '/records/log' => 'records#log', :via => :get
  match '/records/export' => 'records#export', :via => :get
  match '/records/reminder' => 'records#reminder', :via => :get


  match '/care/for' => 'care#receivers', :via => :get

  resources :records

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :health_state

  validates :comment, length: { maximum: 1000 }

  include ActionView::Helpers::JavaScriptHelper

  def self.wordcloud_last_healthy_comment(current_user)
    record_query = Record.where(user_id: current_user).pluck(:comment, :health_state_id)
    r1 = record_query.select { |e| e[0].present? || e[1] != 1}
    r2 = record_query.select { |e| e[0].present? || e[1] != 1}

    r2.shift

    mix = r1.zip(r2)

    comments = mix.select do |e|   e[0][0].present? && e[0][1] == 1 && e[1]  && e[1][1] != 1 end
    comments = comments.map { |c| c[0][0] }
    WordCloud.new(comments)
  end


  def self.wordcloud(current_user, health_state_id=nil)
    record_query = Record.where(user_id: current_user)
    record_query = record_query.where(health_state_id: health_state_id) if health_state_id
    comments = record_query.pluck(:comment).compact
    WordCloud.new(comments)
  end

  def self.health_state_by_hour(current_user)
    time1 = Time.zone.now.in_time_zone("UTC")
    time2 = Time.zone.now.in_time_zone(current_user.time_zone)
    time_difference_in_seconds = time2.utc_offset - time1.utc_offset
    diff_in_hours =  (time_difference_in_seconds/60/60).abs

    query = "select date_part('hour', created_at) as hour, health_state_id, count(*) from records where user_id  = #{current_user.id} group by hour, health_state_id order by hour;"
    result = ActiveRecord::Base.connection.execute(query)
    healthy = [0] * 24
    coming_down = [0] * 24
    recovering = [0] * 24
    sick = [0] * 24
    result.each do |row|
      state = case row["health_state_id"]
                when "1"
                  healthy
                when "2"
                  coming_down
                when "3"
                  sick
                when "4"
                  recovering
                else
                  raise "unexpected health state id"
              end
      state[(row["hour"].to_i+diff_in_hours)%24] = row["count"].to_i
    end
    morning_length = 11
    middle_length = 6
    second_half_start = morning_length + middle_length
    {
        first_half: {
            healthy: healthy.take(morning_length).reduce(&:+),
            coming_down: coming_down.take(morning_length).reduce(&:+),
            sick: sick.take(morning_length).reduce(&:+),
            recovering: recovering.take(morning_length).reduce(&:+)

        },

        middle_of_day: {
            healthy: healthy.drop(morning_length).take(middle_length).reduce(&:+),
            coming_down: coming_down.drop(morning_length).take(middle_length).reduce(&:+),
            sick: sick.drop(morning_length).take(middle_length).reduce(&:+),
            recovering: recovering.drop(morning_length).take(middle_length).reduce(&:+)

        },

        second_half: {
            healthy: healthy.drop(second_half_start).reduce(&:+),
            coming_down: coming_down.drop(second_half_start).reduce(&:+),
            sick: sick.drop(second_half_start).reduce(&:+),
            recovering: recovering.drop(second_half_start).reduce(&:+)
        },

        per_hour: {
          healthy: healthy,
          coming_down: coming_down,
          sick: sick,
          recovering: recovering
        }
    }
  end

  def safe_comment
     escape_javascript Rack::Utils.escape_html comment
  end

end

app/controllers/api/v1/records_controller.rb
module Api
  module V1
    class RecordsController < BaseApiController

      acts_as_token_authentication_handler_for User, fallback_to_devise: false

      before_action :make_sure_valid_user

      def index
        @records = Record.includes(:health_state).where(user: current_user).order('created_at DESC').paginate(:page => params[:page], :per_page => 10).all
        respond_to do |format|
          format.json do
            render :json => @records.to_json(:include => { :health_state => { :only => :name } }, :except => [:user_id, :health_state_id])
          end
        end
      end

      def create
        @record = Record.new(record_params)
        if @record.save

          respond_with(@record, status: 201)
        else
          respond_with(@record, status: 400)
        end
      end

      private

      def make_sure_valid_user
        head(401) unless current_user
      end

      def record_params
        p = params.require(:record).permit(:health_state_id, :comment)
        p.merge(:user => current_user)
      end

    end
  end
end

app/controllers/records_controller.rb
require 'icalendar'

class RecordsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_record, only: [:show, :edit, :update, :destroy]

  before_action :set_health_state, only: [:new, :edit]

  respond_to :html

  def index
    @records = records.paginate(:page => params[:page], :per_page => 10).all
    if @records.size > 0
      @has_stats = @records.last.created_at < 1.days.ago
      @recent_record = @records.first.created_at > 10.minutes.ago
    end


    respond_with(@records)
  end

  def stats
    @records = records.paginate(:page => params[:page], :per_page => 200).all

    @records_stats = RecordsStats.new(@records)

    respond_with(@records)
  end

  def wordcloud
    @wordcloud = {}
    @wordcloud['all'] = Record.wordcloud(current_user).generate
    @wordcloud['healthy'] = Record.wordcloud(current_user, HealthState::HEALTHY).generate
    @wordcloud['coming_down'] = Record.wordcloud(current_user, HealthState::COMING_DOWN).generate
    @wordcloud['sick'] = Record.wordcloud(current_user, HealthState::SICK).generate
    @wordcloud['recovering'] = Record.wordcloud(current_user, HealthState::RECOVERING).generate
    last_healthy_comment = Record.wordcloud_last_healthy_comment(current_user)
    @wordcloud['last_healthy_comment'] = last_healthy_comment.generate
    @last_healthy_comment = last_healthy_comment.comments.uniq
  end

  def aggregates
    @aggregates_stats = Record.health_state_by_hour(current_user)
  end

  def log
    @records = records.where("comment is NOT NULL and comment != ''").paginate(:page => params[:page], :per_page => 10).all
    respond_with(@records)
  end

  def show
    respond_with(@record)
  end

  def new
    @record = Record.new
    respond_with(@record)
  end

  def edit
  end

  def export
    respond_to do |format|
      format.csv {
        set_csv_headers "records.csv"

        self.response_body = RecordsExport.new(current_user).generate
      }
    end
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to action: "index"
    else
      respond_with(@record)
    end
  end

  def update
    @record.update(record_params)
    respond_with(@record)
  end

  def destroy
    @record.destroy
    respond_with(@record)
  end

  def reminder

    cal = Icalendar::Calendar.new

    event_start = DateTime.now+1.days
    event_end = DateTime.now+1.days+5.minutes

    cal.event do |e|
      e.dtstart = Icalendar::Values::DateTime.new event_start
      e.dtend = Icalendar::Values::DateTime.new event_end
      e.url = "http://hecosire.com/records/new"
      e.summary = "How are you?"
      e.description = "Update http://hecosire.com/records/new"
      e.ip_class = "PUBLIC"

      e.rrule = Icalendar::Values::Recur.new("FREQ=DAILY;COUNT=30;")
    end

    cal.publish

    send_data(cal.to_ical, :type => 'text/x-vCalendar', :disposition => 'attachment; filename=event.ics', :filename => 'event.ics')
  end

  private

  def records
    Record.where(user_id: current_user).order('created_at DESC')
  end

  def set_health_state
    @health_state_select = HealthState.all
  end

  def set_record
    @record = Record.where(user: current_user).find(params[:id])
  end

  def record_params
    p = params.require(:record).permit(:health_state_id, :comment)
    p.merge(:user => current_user)
  end

  def set_csv_headers(filename)
    self.response.headers["Content-Type"] ||= "text/csv"
    self.response.headers["Content-Disposition"] = "attachment; filename=#{filename}"
    self.response.headers["Content-Transfer-Encoding"] = "binary"
    self.response.headers["X-Accel-Buffering"] = "no"
    self.response.headers["Cache-Control"] = "no-cache"
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.haml
.panel.panel-default.panel-record
  .panel-body.panel-body-record
    = form_for @record do |f|
      - if @record.errors.any?
        #error_explanation
          %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
          %ul
            - @record.errors.full_messages.each do |msg|
              %li= msg

      .field.form-group
        = f.label 'I am'
        = f.select :health_state_id do
          - @health_state_select.each do |state|
            - option_options = { value: state.id }
            - option_options.merge!(:selected => "selected") if @record.health_state_id == state.id
            = content_tag(:option, state.name, option_options)
      .field.form-group
        = f.label :comment
        = f.text_area :comment
      .actions
        = f.submit 'Save', class: "btn btn-default btn-primary"

app/views/records/aggregates.html.haml
- content_for(:title, "Stats")

.container
  .row
    .col-xs-12
      %h1 How you felt per time of day..
      #chart-aggregates-simpler.chart
  .row
    .col-xs-12
      %h1 How you felt per hour..
      #chart-aggregates.chart
  .row
    .col-xs-12
      %hr
      %a{:href => records_path, :rel => 'nofollow'}
        %button.btn.btn-success
          Go back to your records

- content_for :javascript do
  :javascript
    $(function(){

      var time_of_day = [
                ['Healthy', #{@aggregates_stats[:first_half][:healthy]}, #{@aggregates_stats[:middle_of_day][:healthy]}, #{@aggregates_stats[:second_half][:healthy]}],
                ['Coming down', #{@aggregates_stats[:first_half][:coming_down]}, #{@aggregates_stats[:middle_of_day][:coming_down]}, #{@aggregates_stats[:second_half][:coming_down]}],
                ['Recovering', #{@aggregates_stats[:first_half][:recovering]}, #{@aggregates_stats[:middle_of_day][:recovering]}, #{@aggregates_stats[:second_half][:recovering]}],
                ['Sick', #{@aggregates_stats[:first_half][:sick]}, #{@aggregates_stats[:middle_of_day][:sick]}, #{@aggregates_stats[:second_half][:sick]}]
      ]

      var aggregates = [
                ['Healthy', #{@aggregates_stats[:per_hour][:healthy].join(",")}],
                ['Coming down', #{@aggregates_stats[:per_hour][:coming_down].join(",")}],
                ['Recovering', #{@aggregates_stats[:per_hour][:recovering].join(",")}],
                ['Sick', #{@aggregates_stats[:per_hour][:sick].join(",")}]
              ];


      var chart = c3.generate({
      bindto: "#chart-aggregates",
      data: {
          columns: aggregates,
          type: 'bar'
      },
      bar: {
          width: {
              ratio: 0.5 // this makes bar width 50% of length between ticks
          }
          // or
          //width: 100 // this makes bar width 100px
      }
      });

      var chart_halves = c3.generate({
      bindto: "#chart-aggregates-simpler",
      data: {
          columns: time_of_day,
          type: 'bar'
      },
      bar: {
          width: {
              ratio: 0.5 // this makes bar width 50% of length between ticks
          }
          // or
          //width: 100 // this makes bar width 100px
      }
      });

    });

app/views/records/blog.html.haml
- content_for(:title, "Blog")

- if @records.empty?
  When you create records with comments, they are displayed here.

- unless @records.empty?


  .container
    .row
      .col-xs-12
        %h1 Blog
        %i
          Displaying data going back
          = time_ago_in_words(@records.last.created_at)
        %hr
        - @records.each do |record|
          - if record.comment.present?
            .panel.panel-default
              .panel-heading
                %h3.panel-title
                  %i
                    = record.created_at.to_formatted_s(:long_ordinal)
                  %b
                    = record.health_state
              .panel-body
                = record.comment
                %br
                %br
    .row
      .col-xs-12
        = will_paginate @records
    .row
      .col-xs-12
        %hr
        %a{:href => records_path, :rel => 'nofollow'}
          %button.btn.btn-success
            Go back to your records

app/views/records/edit.html.haml
- content_for(:title, "Editing record")

%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
- content_for(:title, "Records")

.container
  .row
    .col-xs-12.col-sm-6
      - unless @recent_record
        %h1 How are you feeling?
        %a{:href => new_record_path, :rel => 'nofollow'}
          %button.btn.btn-primary
            = fa_icon "pencil"
            New Record
      - if @recent_record
        %h1 Good job!
        %p Track every day to gather valuable data about yourself.
        %a{:href => records_reminder_path, :rel => 'nofollow', :format => :ics}
          %button.btn.btn-success
            = fa_icon "calendar"
            Remind me tomorrow
        %a{:href => new_record_path, :rel => 'nofollow'}
          %button.btn
            New Record

- unless @records.empty?
  .container
    .row
      .col-xs-12
        %h1 How you felt..
    .row
      .col-xs-12.col-sm-6

        %table.table
          %thead
            %tr
              %th Date
              %th Health state
              %th
              %th
              %th

          %tbody
            - @records.each do |record|
              %tr
                %td
                  = time_ago_in_words(record.created_at)
                  ago
                %td= record.health_state
                %td= link_to 'Show', record
                %td= link_to 'Edit', edit_record_path(record)
                %td= link_to '<i class="fa fa-trash"></i>'.html_safe, record, :method => :delete, :data => { :confirm => 'Are you sure?' }

        = will_paginate @records

        %br
      .col-xs-12.col-sm-6
        - if @has_stats
          %p
            We have prepared some useful graphs and stats just for you..
          %a{:href => records_stats_path, :rel => 'nofollow'}
            %button.btn.btn-success
              = fa_icon "pie-chart"
              See my stats
          %a{:href => records_log_path, :rel => 'nofollow'}
            %button.btn.btn-success
              See my personal log
          %a{:href => records_wordcloud_path, :rel => 'nofollow'}
            %button.btn.btn-success
              See my word cloud
        - else
          %p
            Looks like you are new to HeCoSiRe..
          %p
            Keep tracking and in few days we will prepare stats for you.
          %button.btn.btn-disabled
            = fa_icon "pie-chart"
            See my stats
          %button.btn.btn-disabled
            See my personal log
          %button.btn.btn-disabled
            See my word cloud
    .row
      .col-xs-12
        %hr
          %a{:href => "#{records_export_path}.csv", :rel => 'nofollow'}
            Export records as csv file
    .row
      .col-xs-12
        %h1 People you care for
        %a{:href => care_for_path, :rel => 'nofollow'}
          %button.btn.btn-success
            See people you care for

app/views/records/log.html.haml
- content_for(:title, "Blog")

- if @records.empty?
  When you create records with comments, they are displayed here.

- unless @records.empty?


  .container
    .row
      .col-xs-12
        %h1 Personal log
        %i
          Displaying data going back
          = time_ago_in_words(@records.last.created_at)
        %hr
        - @records.each do |record|
          - if record.comment.present?
            .panel.panel-default
              .panel-heading
                %h3.panel-title
                  %i
                    = record.created_at.to_formatted_s(:long_ordinal)
                  %b
                    = record.health_state
              .panel-body
                = record.comment
                %br
                %br
    .row
      .col-xs-12
        = will_paginate @records
    .row
      .col-xs-12
        %hr
        %a{:href => records_path, :rel => 'nofollow'}
          %button.btn.btn-success
            Go back to your records

app/views/records/new.html.haml
- content_for(:title, "New record")

%h1 How are you feeling?

= render 'form'

= link_to 'Cancel', records_path

app/views/records/show.html.haml
- content_for(:title, "Record")

%p#notice= notice

%p
  %b You felt:
  = @record.health_state

- if @record.comment.present?
  %p
    %b Your comments:
    = @record.comment


= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path

app/views/records/stats.html.haml
- content_for(:title, "Records stats")

- unless @records.empty?

  = will_paginate @records

  .container
    .row
      .col-xs-12
        %h1 How you felt..
        Displaying data going back
        = time_ago_in_words(@records.last.created_at)
    - if @records_stats.has_data_going_back?(7)
      .row
        .col-xs-12
          %h2 Last week
          #chart-time-week.chart
          #chart-week.chart
    - if @records_stats.has_data_going_back?(31)
      .row
        .col-xs-12
          %h2 Last month
          #chart-time-month.chart
          #chart-month.chart
    - if @records_stats.has_data_going_back?(365)
      .row
        .col-xs-12
          %h2 Last year
          #chart-time-year.chart
          #chart-year.chart

    .row
      .col-xs-12
        %a{:href => records_aggregates_path}
          See aggregate values
        %hr
        %a{:href => records_path, :rel => 'nofollow'}
          %button.btn.btn-success
            Go back to your records

- content_for :javascript do
  :javascript
    $(function(){

      var commentsWeek = [#{@records_stats.comments(7)}];
      var commentsMonth = [#{@records_stats.comments(31)}];
      var commentsYear = [#{@records_stats.comments(365)}];

      var pieChartLastWeekColumns = [
                ['Healthy', #{@records_stats.stats(7)[:healthy]}],
                ['Coming down', #{@records_stats.stats(7)[:coming_down]}],
                ['Sick', #{@records_stats.stats(7)[:sick]}],
                ['Recovering', #{@records_stats.stats(7)[:recovering]}]
              ];

      var linesChartLastWeekColumns = [
                ['x',
                #{@records_stats.dates_for_timechart(7)}
                ],
                ['y',
                #{@records_stats.states_for_timechart(7)}
                ]

            ];

      var pieChartLastYearColumns = [
                ['Healthy', #{@records_stats.stats(365)[:healthy]}],
                ['Coming down', #{@records_stats.stats(365)[:coming_down]}],
                ['Sick', #{@records_stats.stats(365)[:sick]}],
                ['Recovering', #{@records_stats.stats(365)[:recovering]}]
              ];

      var linesChartLastYearColumns = [
                ['x',
                #{@records_stats.dates_for_timechart(365)}
                ],
                ['y',
                #{@records_stats.states_for_timechart(365)}
                ]

            ];      

      var pieChartLastMonthColumns = [
                ['Healthy', #{@records_stats.stats(31)[:healthy]}],
                ['Coming down', #{@records_stats.stats(31)[:coming_down]}],
                ['Sick', #{@records_stats.stats(31)[:sick]}],
                ['Recovering', #{@records_stats.stats(31)[:recovering]}]
              ];

      var linesChartLastMonthColumns = [
                ['x',
                #{@records_stats.dates_for_timechart(31)}
                ],
                ['y',
                #{@records_stats.states_for_timechart(31)}
                ]

            ];


      Hecosire.generateStatCharts('#chart-week', pieChartLastWeekColumns, '#chart-time-week', linesChartLastWeekColumns, commentsWeek);
      
      Hecosire.generateStatCharts('#chart-month', pieChartLastMonthColumns, '#chart-time-month', linesChartLastMonthColumns, commentsMonth);

      Hecosire.generateStatCharts('#chart-year', pieChartLastYearColumns, '#chart-time-year', linesChartLastYearColumns, commentsYear);

    });

app/views/records/wordcloud.html.haml
- content_for(:title, "Word cloud")

.container
  - unless @wordcloud['last_healthy_comment'].empty?
    .row
      .col-xs-12
        %h1 Words before feeling sick
        #wordcloud-before-sick.wordcloud
    .row
      .col-xs-12
        %h1 Comments before feeling sick
        - @last_healthy_comment.each do |c|
          %p
            = c
  - unless @wordcloud['all'].empty?
    .row
      .col-xs-12
        %h1 Word cloud
        #wordcloud-all.wordcloud
  - unless @wordcloud['healthy'].empty?
    .row
      .col-xs-12
        %h1 Word cloud healthy
        #wordcloud-healthy.wordcloud
  - unless @wordcloud['coming_down'].empty?
    .row
      .col-xs-12
        %h1 Word cloud coming down
        #wordcloud-coming-down.wordcloud
  - unless @wordcloud['sick'].empty?
    .row
      .col-xs-12
        %h1 Word cloud sick
        #wordcloud-sick.wordcloud
  - unless @wordcloud['recovering'].empty?
    .row
      .col-xs-12
        %h1 Word cloud recovering
        #wordcloud-recovering.wordcloud

  .row
    .col-xs-12
      %hr
      %a{:href => records_path, :rel => 'nofollow'}
        %button.btn.btn-success
          Go back to your records
%script
  - %w(all healthy coming_down sick recovering last_healthy_comment).each do |state|
    var word_array_#{state} = [
    - @wordcloud[state].each do |key, value|
      {text: "#{key}", weight: #{value}},
    ];


- content_for :javascript do
  :javascript
    $(function(){
       $("#wordcloud-all").jQCloud(word_array_all);
       $("#wordcloud-healthy").jQCloud(word_array_healthy);
       $("#wordcloud-coming-down").jQCloud(word_array_coming_down);
       $("#wordcloud-sick").jQCloud(word_array_sick);
       $("#wordcloud-recovering").jQCloud(word_array_recovering);
       $("#wordcloud-before-sick").jQCloud(word_array_last_healthy_comment);
    });